name: NodeJS with Parcel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Get Latest code
      uses: actions/checkout@v2
      
    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Build project
      run: |
        npm install
        npm run build

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{secrets.SITE_SERVER}}
        username: ${{secrets.SITE_USERNAME}}
        password: ${{secrets.SITE_PASS}}
        local-dir: ./dist/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          
